workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

stages:
  - json-to-html
  - html-to-pdf
  - deploy

cache:
  key: node_modules
  paths:
    - node_modules

before_script:
  - npm ci

json_to_html:
  image: 
    name: node:22
    docker:
      user: root
  stage: json-to-html
  script:
    - npm run html-export
  artifacts:
    when: on_success
    expire_in: 2 days
    paths:
      - "resume*.html"
  environment: production

html_to_pdf:
  image:
    name: ghcr.io/puppeteer/puppeteer:22.15.0
    docker:
      user: root
  stage: html-to-pdf
  dependencies:
    - json_to_html
  script:
    - npx puppeteer browsers install chrome
    - npm run pdf-export
  artifacts:
    when: on_success
    expire_in: 2 days
    paths:
      - "resume*.pdf"
  environment: production

pages:
  image:
    name: node:22
    docker:
      user: root
  stage: deploy
  dependencies:
    - json_to_html
    - html_to_pdf
  script:
    - cp photo.jpg resume*.html resume*.pdf public/
    - cp public/resume0.html public/index.html
    - find . -name "Sample*.pdf" -exec cp '{}' public/ \;
  artifacts:
    when: on_success
    paths:
      - public
  publish: public
  environment: production