workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

stages:
  - json-to-html
  - html-to-pdf
  - deploy

cache:
  key: node_modules
  paths:
    - node_modules

before_script:
  - npm install

json_to_html:
  image: 
    name: node:20.11.1
    docker:
      user: root
  stage: json-to-html
  script:
    - npx resumed --theme jsonresume-theme-even --output index.html
    - npx resumed --theme @jsonresume/jsonresume-theme-class --output matthew-nestor.html
    - npx resumed resume-retail.json --theme jsonresume-theme-even --output index-retail.html
    - npx resumed resume-retail.json --theme @jsonresume/jsonresume-theme-class --output matthew-nestor-retail.html
  artifacts:
    when: on_success
    expire_in: 2 days
    paths:
      - "index.html"
      - "matthew-nestor.html"
      - "index-retail.html"
      - "matthew-nestor-retail.html"
  environment: production

html_to_pdf:
  image:
    name: ghcr.io/puppeteer/puppeteer:22.6.3
    docker:
      user: root
  stage: html-to-pdf
  dependencies:
    - json_to_html
  script:
    - npx puppeteer browsers install chrome
    - npm run pdf-export
  artifacts:
    when: on_success
    expire_in: 2 days
    paths:
      - "resume.pdf"
      - "matthew-nestor.pdf"
      - "resume-retail.pdf"
      - "matthew-nestor-retail.pdf"
  environment: production

pages:
  image:
    name: node:20.11.1
    docker:
      user: root
  stage: deploy
  dependencies:
    - json_to_html
    - html_to_pdf
  script:
    - cp photo.jpg index.html matthew-nestor.html resume.pdf matthew-nestor.pdf index-retail.html matthew-nestor-retail.html resume-retail.pdf matthew-nestor-retail.pdf public/
    - find . -name "Sample*.pdf" -exec cp '{}' public/ \;
  artifacts:
    when: on_success
    paths:
      - public
  publish: public
  environment: production