name: GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Build
        run: |
          npm ci
          npm run html-export
          npx puppeteer browsers install chrome && npm run pdf-export
          cp photo.jpg public/
          find . -maxdepth 1 -name "resume*.html" -exec mv '{}' public/ \;
          cp public/resume0.html public/index.html
          find . -maxdepth 1 -name "resume*.pdf" -exec mv '{}' public/ \;
          find . -maxdepth 1 -name "Sample*.pdf" -exec cp '{}' public/ \;

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public